In [ ]:
import numpy as np
arr = np.zeros(7, dtype = int)
arr[2] = 9
print(arr.size)
print(arr[2])

7
9


In [ ]:
import numpy as np

arr = np.array([3, 5, 6, 7, 7])
print(arr)

[3 5 6 7 7]


In [ ]:
import numpy as np
arr = np.array([3, 5, 6, 7, 7, 3, 5, 4])
for i in range(0, arr.size):
  print(arr[i], end=" ")

3 5 6 7 7 3 5 4 

In [ ]:
import numpy as np
i = 0
arr = np.array([3, 5, 7, 3, 7, 5, 6, 9])
while i<len(arr):
  print(arr[i], end=" ")
  i += 1

3 5 7 3 7 5 6 9 

In [ ]:
import numpy as np
length = int(input())
arr = np.zeros(length, dtype= int)
for i in range(0, length):
  value = int(input())
  arr[i] = value
print(arr)

5
1
2
3
4
5
[1 2 3 4 5]


In [ ]:
import numpy as np

arr1 = np.zeros(shape = (3, 5), dtype= str)
arr2 = np.zeros(shape = (3, 5), dtype= int)

print(arr1)
print(arr2)


[['' '' '' '' '']
 ['' '' '' '' '']
 ['' '' '' '' '']]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [ ]:
import numpy as np
arr = np.array([[2, 5, 67, 4], [4, 6, 6, 54], [4, 6, 7, 4]])
print(arr)
print(arr[2][1])
print(arr[1][3])

[[ 2  5 67  4]
 [ 4  6  6 54]
 [ 4  6  7  4]]
6
54


In [ ]:
import numpy as np
arr = np.array([[3, 4, 6, 7], [4, 6, 7, 8]])
print(arr)

[[3 4 6 7]
 [4 6 7 8]]


In [ ]:
import numpy as np
list = [["araf", "zaman"], ["aayat", "zaman"], ["amirun", "nahin"]]
arr = np.array(list)

print(arr)

[['araf' 'zaman']
 ['aayat' 'zaman']
 ['amirun' 'nahin']]


In [ ]:
import numpy as np
list = [3, 5, 3, 7, 4, 78, 8, 9, 10]

arr = np.array(list)
for i in range(0, len(arr)):
  for j in range(0, len(arr)-i-1):
    if arr[j] > arr[j+1]:
      temp = arr[j]
      arr[j] = arr[j+1]
      arr[j+1] = temp
print(arr)


[ 3  3  4  5  7  8  9 10 78]


In [ ]:
import numpy as np
list = [3, 4, 6, 2, 7, 4]
arr = np.array(list)
print(arr, type(arr))

[3 4 6 2 7 4] <class 'numpy.ndarray'>


In [ ]:
import numpy as np

arr = np.array([[3, 4, 6, 7], [4, 6, 7, 8]])
r_len = arr.shape[0]
c_len = arr.shape[1]

for i in range(0, r_len):
  for j in range(0, c_len):
    print(arr[i][j], end=" ")
  print()

3 4 6 7 
4 6 7 8 


In [ ]:
import numpy as np

arr = np.array([3, 4, 3, 5, 6])
i = 0
while i<len(arr):
  print(arr[i])
  i += 1

3
4
3
5
6


In [ ]:
import numpy as np
l = []
arr = np.array([3, 5, 7, 8])
for i in range(len(arr)-1, -1, -1):
  l.append(arr[i])
new_arr = np.array(l)
print(new_arr)

[8 7 5 3]


In [ ]:
list = [3, 4, 6, 8, 3, 6]
new_list = []
for i in range(len(list)-1, -1, -1):
  new_list.append(list[i])
print(new_list)

[6, 3, 8, 6, 4, 3]


In [ ]:
#creating a multidimensional array
#2d array creation
import numpy as np
arr = np.zeros(shape = (2, 3), dtype = int)
print(arr)

[[0 0 0]
 [0 0 0]]


In [ ]:
#3d array creation
import numpy as np
arr = np.zeros(shape = (2, 3, 4), dtype = int)
print(arr)


[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


In [ ]:
import numpy as np
arr = np.array([[3, 4, 6, 3], [3, 5, 2, 7]])
print(arr)

[[3 4 6 3]
 [3 5 2 7]]


In [ ]:
import numpy as np
arr = np.array([[3, 4, 6], [3, 5, 7]])
print(arr)
print(type(arr))
print(len(arr))
print(arr.size)
print(arr.dtype)
print(arr.shape)

[[3 4 6]
 [3 5 7]]
<class 'numpy.ndarray'>
2
6
int64
(2, 3)


In [ ]:
import numpy as np
arr = np.array([[3, 4, 5, 4], [3, 5, 7, 8]])
print(arr[1][2])
print(arr.shape)
row = arr.shape[0]
col = arr.shape[1]
print(row)
print(col)
print(f"it is a ({row}x{col}) matrix")
print(arr.size)

7
(2, 4)
2
4
it is a (2x4) matrix
8


In [ ]:
#iteration of 2d matrix
import numpy as np
arr = np.array([[3, 4, 6, 5], [3, 5, 6, 8]])
row = arr.shape[0]
col = arr.shape[1]
for i in range(row):
  for j in range(col):
    print(arr[i][j], end=" ")
  print()

3 4 6 5 
3 5 6 8 


In [ ]:
#scaler and matrix multiplication
import numpy as np
num = int(input())
arr = np.array([[3, 4, 2, 6], [3, 6, 8, 1]])
row = arr.shape[0]
col = arr.shape[1]
for i in range(row):
  for j in range(col):
    arr[i][j] = num * arr[i][j]
print(arr)

2
[[ 6  8  4 12]
 [ 6 12 16  2]]


In [ ]:
#take row and col as user input
#make a 2d matrix by taking user input values of each cell
import numpy as np
row = int(input())
col = int(input())
arr = np.zeros(shape = (row, col), dtype = int)

for i in range(row):
  for j in range(col):
    num = int(input())
    arr[i][j] = num

print(arr)

2
3
1
2
3
4
5
6
[[1 2 3]
 [4 5 6]]


In [ ]:
#flatten the 2d array
import numpy as np
def flatten(arr):
  count = 0
  new_arr = np.zeros(arr.size, dtype = int)
  row = arr.shape[0]
  col = arr.shape[1]
  for i in range(row):
    for j in range(col):
      new_arr[count] = arr[i][j]
      count += 1
  return new_arr

arr = np.array([[1, 2, 3, 5, 6], [2, 3, 4, 5, 7]])
print(flatten(arr))

[1 2 3 5 6 2 3 4 5 7]


In [ ]:
#check if the matrix is an identity matrix
import numpy as np
A = np.array([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]])
ide_mat = True
row = A.shape[0]
col = A.shape[1]
for i in range(row):
  for j in range(col):
    if i == j and A[i][j] != 1:
      ide_mat = False
    elif i != j and A[i][j] != 0:
      ide_mat = False
if ide_mat:
  print("Identity Matrix")
else:
  print("Not an Identity Matrix")

Identity Matrix


In [ ]:
#calc the abs diff between the diagonals of a 2d matrix
import numpy as np
A = np.array([[1, 5, 12, 1], [2, -4, 6, 7], [3, 8, 5, 9], [3, 5, 23, -6]])
row = A.shape[0]
col = A.shape[1]
l_to_r = 0
r_to_l = 0

for i in range(row):
  for j in range(col):
    if i==j:
      l_to_r += A[i][j]

for i in range(row):
  for j in range(col):
    if i+j==row-1:
      r_to_l += A[i][j]


print(abs(l_to_r-r_to_l))

22


In [ ]:
#transpose of a 2d matrix
import numpy as np
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
row = A.shape[0]
col = A.shape[1]
tA = np.zeros(shape = (col, row), dtype = int)
for i in range(row):
  for j in range(col):
    tA[j][i] = A[i][j]
print(tA)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [ ]:
#matrix multiplication
#transpose of a 2d matrix
import numpy as np
A = np.array([[1, 2, 3, 4], [1, 4, 9, 16]])
row = A.shape[0]
col = A.shape[1]
tA = np.zeros(shape = (col, row), dtype = int)
for i in range(row):
  for j in range(col):
    tA[j][i] = A[i][j]
print(tA)

row_tA = tA.shape[0]
col_tA = tA.shape[1]
mul_mat = np.zeros(shape = (row, col_tA), dtype = int)
print(mul_mat)

[[ 1  1]
 [ 2  4]
 [ 3  9]
 [ 4 16]]
[[0 0]
 [0 0]]


In [ ]:
#matrix multiplication
import numpy as np
A = np.array([[1, 2, 3, 4], [1, 4, 9, 16]])
row_A = A.shape[0]
col_A = A.shape[1]
tA = np.zeros(shape = (col_A, row_A), dtype = int)
for i in range(row_A):
  for j in range(col_A):
    tA[j][i] = A[i][j]

row_tA = tA.shape[0]
col_tA = tA.shape[1]
mul_mat = np.zeros(shape = (row_tA, col_A), dtype = int)

for i in range(row_tA):
  for j in range(col_A):
    sum = 0
    for k in range(col_tA):
      sum += tA[i][k] * A[k][j]
    mul_mat[i][j] = sum
print(mul_mat)

[[  2   6  12  20]
 [  6  20  42  72]
 [ 12  42  90 156]
 [ 20  72 156 272]]


In [ ]:
#inserion sort
import numpy as np
arr = np.array([1, 3, 7, 5, 9, 0, 6, 4])
for i in range(1, arr.size):
  current_value = arr[i]
  neighbour_index = i-1
  while neighbour_index >= 0 and current_value < arr[neighbour_index]:
    arr[neighbour_index + 1] = arr[neighbour_index]
    neighbour_index -= 1
  arr[neighbour_index + 1] = current_value

print(arr)

[0 1 3 4 5 6 7 9]


In [ ]:
#selection sort
import numpy as np
arr = np.array([1, 3, 7, 5, 9, 0, 6, 4])
for i in range(arr.size):
  min_idx = i
  for j in range(i+1, arr.size):
    if arr[j] < arr[min_idx]:
      min_idx = j
  temp = arr[i]
  arr[i] = arr[min_idx]
  arr[min_idx] = temp
print(arr)


[0 1 3 4 5 6 7 9]


In [ ]:
import numpy as np

A = np.array([[1, 2, 3, 4], [1, 4, 9, 16]])

row_A, col_A = A.shape

tA = np.zeros(shape=(col_A, row_A), dtype=int)

for i in range(row_A):
    for j in range(col_A):
        tA[j][i] = A[i][j]

row_tA, col_tA = tA.shape

mul_mat = np.zeros(shape=(row_tA, col_A), dtype=int)

for i in range(row_tA):
    for j in range(col_A):
        sum = 0
        for k in range(col_tA):
            sum += tA[i][k] * A[k][j]
        mul_mat[i][j] = sum

print(mul_mat)


[[  2   6  12  20]
 [  6  20  42  72]
 [ 12  42  90 156]
 [ 20  72 156 272]]


In [ ]:
#multiplication of A and B matrix
import numpy as np
def matrixMultiplication(A, B):
  row_A = A.shape[0]
  col_A = A.shape[1]
  row_B = B.shape[0]
  col_B = B.shape[1]
  mul_mat = np.zeros(shape = (row_A, col_B), dtype = int)
  for i in range(row_A):
    for j in range(col_B):
      sum = 0
      for k in range(col_A):
        sum += A[i][k] * B[k][j]
      mul_mat[i][j] = sum
  return mul_mat

B = np.array([[1, 1], [2, 4], [3, 9], [4, 16]])
A = np.array([[1, 2, 3, 4], [1, 4, 9, 16]])
print(matrixMultiplication(B, A))


[[  2   6  12  20]
 [  6  20  42  72]
 [ 12  42  90 156]
 [ 20  72 156 272]]


In [ ]:
#lab 7 task 11
import numpy as np
A = np.array([[6, 3], [1, 5]])
row = A.shape[0]
col = A.shape[1]
abs_value = abs(row-col)
remainder = abs_value % row
sum = 0
if remainder == 0:
  for j in range(col):
    sum += A[0][j]
elif remainder == 1:
  for j in range(col):
    sum += A[1][j]
elif remainder == 2:
  for j in range(col):
    sum += A[0][j]
avg = sum/col

new_A = np.zeros(shape = (row, col), dtype = float)
for i in range(row):
  for j in range(col):
    new_A[i][j] = avg * A[i][j]
print(new_A)

[[27.  13.5]
 [ 4.5 22.5]]
