In [ ]:
#https://www.youtube.com/playlist?list=PLCC34OHNcOtpalASMlX2HHdsLNipyyhbK
#https://www.youtube.com/playlist?list=PLjVLYmrlmjGfgBKkIFBkMNGG7qyRfo00W
#This is a combined note based on both of this playlists

In [ ]:
#Numpy is a library for python adding support for large, multi-dimensional arrays and matrices
#numpy is a python library that provides multidimensional array object, various derived objects
#an array is a grid of values and it contains information about the raw data
#array is faster and convenient to use compared to list and takes less memory

In [ ]:
#an array in python is kinda like list but have only one type of data types in one single array
#Numpy stands for Numeric Python
#it is different to list in the way that list can have multiple data types so the computational time is longer whereas
#numpy array have only one data type so this is faster
#the default datatype of numpy is 'float64'

In [ ]:
#importing numpy array
import numpy as np

In [ ]:
#Creating a numpy array
np1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(np1)
print(type(np1))

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [ ]:
#To see the shape of the array
print(np1.shape)

#to see the dimension of the array
print(np1.ndim)

np2 = np.array([[1, 2, 3], [4, 5, 6]])
print(np2.ndim)

(9,)
1
2


In [ ]:
#arange - creates array for us without explicitly writing it
#it can take range, steps
np1 = np.arange(10) #10 is the range
print(np1)
np2 = np.arange(0, 10, 2) #0 and 10 are the range and 2 is the step
print(np2)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [ ]:
#creating an identity matrix/array
np1 = np.eye(5)
print(np1)

#creating an multidimensionial identity array
np2 = np.eye(3, 4)
print(np2)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [ ]:
#creating an array with zero as the element
np1 = np.zeros(10, dtype="int")
print(np1)
np2 = np.zeros(10, dtype="float")
print(np2)

#multidimensional zeros
np3 = np.zeros((2, 3), dtype="int")
print(np3)

[0 0 0 0 0 0 0 0 0 0]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0 0 0]
 [0 0 0]]


In [ ]:
#creating an array with one as the element
np1 = np.ones(10, dtype="int")
print(np1)
np2 = np.ones(10, dtype="float")
print(np2)

#multidimensional ones
np3 = np.ones((2, 3), dtype="int")
print(np3)

[1 1 1 1 1 1 1 1 1 1]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1 1 1]
 [1 1 1]]


In [ ]:
#empty array
np1 = np.empty(10, dtype="int")
print(np1)
np2 = np.empty(10, dtype="float")
print(np2)

#multidimensional empty
np3 = np.empty((2, 3), dtype="int")
print(np3)

[4607182418800017408 4607182418800017408 4607182418800017408
 4607182418800017408 4607182418800017408 4607182418800017408
 4607182418800017408 4607182418800017408 4607182418800017408
 4607182418800017408]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[     96334627843022                   0 9151593729524498950]
 [9151593729524498952 9151593729524498952 9151593729524498952]]


In [ ]:
#creating an array with values that are spaced linearly in a specific interval
#endpoint- if True, stop is the last sample. Otherwise, it is not included. Default is True
#retstep(return step)- if True, return (samples, step), where step is the spacing between samples.
np1 = np.linspace(1, 10, num=10, dtype="int64", endpoint=False, retstep=True)
print(np1)

#here's much simpler version
np2 = np.linspace(1, 10, num=10)
print(np2)

(array([1, 1, 2, 3, 4, 5, 6, 7, 8, 9]), 0.9)
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [ ]:
#creating numpy arrays with random numbers
#rand - it generates numbers between 0 to 1
#ranf - similar to rand but it does not exclude 1 i.e. [0.0, 1.0)
np1 = np.random.rand(10)
print(np1)

#multidimensional array with random numbers-2d
np2 = np.random.rand(2, 5)
print(np2)

#multidimensional array with random numbers-3d
np3 = np.random.rand(2, 2, 2)
print(np3)

#ranf
np4 = np.random.ranf(7)
print(np4)

[0.91714963 0.64487141 0.45989961 0.74126355 0.98122118 0.44538171
 0.42016716 0.67627013 0.09196083 0.0107995 ]
[[0.27570052 0.89130757 0.12001237 0.64983147 0.54000361]
 [0.0189533  0.71279137 0.62575245 0.17721323 0.68075505]]
[[[0.62425921 0.01392571]
  [0.78773731 0.97675304]]

 [[0.36521675 0.65711214]
  [0.16777611 0.31347537]]]
[0.06807678 0.83267983 0.97463305 0.22804905 0.4467637  0.7636058
 0.49735411]


In [ ]:
#randn - this generates numbers that are close to zero
#it can be positive or negative
np1 = np.random.randn(10)
print(np1)

[-1.44677671 -0.10352117 -0.81473289  0.2930584   1.25517268  0.34446396
 -0.62207521 -1.29822384  0.41718975 -0.17353359]


In [ ]:
#randint - it generates random int number between given range
#np.random.randint(startswith, endswith, total_numbers)
np1 = np.random.randint(1, 10, 10)
print(np1)

#it can be multidimensional-2d
np2 = np.random.randint(1, 10, (2, 3))
print(np2)

#it can be multidimensional-3d
np3 = np.random.randint(1, 10, (2, 2, 2))
print(np3)

[6 9 8 8 1 1 5 8 6 8]
[[7 1 5]
 [1 5 4]]
[[[9 4]
  [3 5]]

 [[6 3]
  [9 3]]]


In [ ]:
#if we want a specific number instead of zero
#the first one takes the shape or how the array will be like
#the second one takes the number or the element
np1 = np.full(10, 5)
print(np1)

#Multidimensional full
np2 = np.full((2, 3), 5)
print(np2)

[5 5 5 5 5 5 5 5 5 5]
[[5 5 5]
 [5 5 5]]


In [ ]:
#convert python list to numpy array
lst = [1, 2, 45, 67 , 75]
np1 = np.array(lst)
print(np1)

[ 1  2 45 67 75]


In [ ]:
#accessing numpy array
#this is same as accessing elements in list
np1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(np1[0])
print(np1[1])

1
2


In [ ]:
#slicing numpy arrays
#as ususal in python first one is the inital and last one is the final excluding the final'th number
np1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(np1[3:6])
print(np1[0:3])
print(np1[1:4])

#return negative slices
print(np1[-3:-1])

[4 5 6]
[1 2 3]
[2 3 4]
[7 8]


In [ ]:
#return from something till the end of the array
np1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(np1[3:])

#using negative slicing
print(np1[-5:])

#return from the beginning till something
print(np1[:8])

#using negative slicing
print(np1[:-6])

[4 5 6 7 8 9]
[5 6 7 8 9]
[1 2 3 4 5 6 7 8]
[1 2 3]


In [ ]:
#slicing with steps
np1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
#from start to 10th index with step 2
print(np1[0:10:2])

#from 2nd index to the end with step 3
print(np1[2::3])

#from start to the end with step 2
print(np1[::2])

[1 3 5 7 9]
[3 6 9]
[1 3 5 7 9]


In [ ]:
#creating a 2d array
np1 = np.array([[1, 2], [3, 4], [5, 6], [7 ,8], [9, 10]])
print(np1)
print(np1.shape)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
(5, 2)


In [ ]:
#accessing an element from a 2d array
#let's say we pull 7
np1 = np.array([[1, 2], [3, 4], [5, 6], [7 ,8], [9, 10]])
print(np1[3, 0])

7


In [ ]:
#slice a 2d array
np1 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(np1[1, 2:5])

#here is another kind of slicing
np2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(np2[0:2, 1:4])

[ 8  9 10]
[[2 3 4]
 [6 7 8]]


In [ ]:
#Universal function(ufunc)
#some are given here. for other ufunc functions-->
#https://numpy.org/doc/stable/reference/ufuncs.html
np1 = np.array([-3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(np1)

[-3 -2 -1  0  1  2  3  4  5  6  7  8  9]


In [ ]:
#square root of each element
print(np.sqrt(np1[3:]))

#sign positive or negative
print(np.sign(np1))

#sort
print(np.sort(np1))

#variance
print(np.var(np1))

#standard deviation
print(np.std(np1))

#median
print(np.median(np1))

#mean
print(np.mean(np1))

#min/max
print("Min: ", np.min(np1))
print("Max: ", np.max(np1))

#log of each element
print(np.log(np1[4:]))

#absolute value of each element
print(np.abs(np1))

#exponential of each element
print(np.exp(np1))

#sin of each element
print("sin: ", np.sin(np1))

#cos of each element
print("cos: ", np.cos(np1))

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
[-1 -1 -1  0  1  1  1  1  1  1  1  1  1]
[-3 -2 -1  0  1  2  3  4  5  6  7  8  9]
14.0
3.7416573867739413
3.0
3.0
Min:  -3
Max:  9
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]
[3 2 1 0 1 2 3 4 5 6 7 8 9]
[4.97870684e-02 1.35335283e-01 3.67879441e-01 1.00000000e+00
 2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03]
sin:  [-0.14112001 -0.90929743 -0.84147098  0.          0.84147098  0.90929743
  0.14112001 -0.7568025  -0.95892427 -0.2794155   0.6569866   0.98935825
  0.41211849]
cos:  [-0.9899925  -0.41614684  0.54030231  1.          0.54030231 -0.41614684
 -0.9899925  -0.65364362  0.28366219  0.96017029  0.75390225 -0.14550003
 -0.91113026]


In [ ]:
#Copy vs View
#This is just basic python where if we do not copy it just basically indicates the same memory location
#so if we change one it changes all the variables data as all the variable indicates the same memory location

In [ ]:
##view
np1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
np2 = np1.view()
print(np1)
print(np2)

np1[0] = 100
print(np1)
print(np2)

In [ ]:
#Copy
np1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
np3 = np1.copy()
print(np1)
print(np3)

np1[1] = 200
print(np1)
print(np3)

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[  1 200   3   4   5   6   7   8   9]
[1 2 3 4 5 6 7 8 9]


In [ ]:
#shape and reshape numpy arrays
np1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(np1)
print(np1.shape)

np2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(np2)
print(np2.shape)

[1 2 3 4 5 6 7 8 9]
(9,)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)


In [ ]:
#reshaping
np1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(np1)
print(np1.shape)

#let's say we want 3 rows and 4 cols
np2 = np1.reshape(3, 4)
print(np2)
print(np2.shape)

#or we want 4 rows and 3 cols
np3 = np1.reshape(4, 3)
print(np3)
print(np3.shape)

# Setting to -1 automatically decides the number of rows or cols
np1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(np1)
print(np1.shape)

np4 = np1.reshape(2, -1)
print(np4)

np5 = np1.reshape(-1, 2)
print(np5)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)
[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [ ]:
#reshaping to 2d array
np1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18])
print(np1)
print(np1.shape)

#if we want 3 2d arrays with 2 rows and 3 cols
np2 = np1.reshape(3, 2, 3)
print(np2)
print(np2.shape)

#and if we want 3 2d arrays with 3 rows and 2 cols
np3 = np1.reshape(3, 3, 2)
print(np3)
print(np3.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
(18,)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
(3, 2, 3)
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]]
(3, 3, 2)


In [ ]:
#if we want to flatten the array
np1 = np.array([[[1, 2], [3, 4]], [[5 ,6], [7 ,8]]])
print(np1)
print(np1.shape)
np2 = np1.reshape(-1)
print(np2)
print(np2.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)
[1 2 3 4 5 6 7 8]
(8,)


In [ ]:
#iterating through numpy arrays
#iterating through a 1d array
np1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(np1)
for i in np1:
  print(i, end=" ")

[1 2 3 4 5 6 7 8 9]
1 2 3 4 5 6 7 8 9 

In [ ]:
#iterating through a 2d array
np1 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(np1)
for i in np1:
  for j in i:
    print(j, end=" ")

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
1 2 3 4 5 6 7 8 9 10 

In [ ]:
#iterating through a 3d array
np1 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(np1)
for i in np1:
  for j in i:
    for k in j:
      print(k, end=" ")

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)
4
1 2 3 4 5 6 7 8 

In [ ]:
#np.nditer()
np1 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(np1)
for i in np.nditer(np1):
  print(i, end=" ")
print()
#ndnumrated - this gives the index  of the element also
np2 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(np2)
for i, j in np.ndenumerate(np2):
  print("index: "+ str(i) + " data: "+ str(j))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
1 2 3 4 5 6 7 8 
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
index: (0, 0, 0) data: 1
index: (0, 0, 1) data: 2
index: (0, 1, 0) data: 3
index: (0, 1, 1) data: 4
index: (1, 0, 0) data: 5
index: (1, 0, 1) data: 6
index: (1, 1, 0) data: 7
index: (1, 1, 1) data: 8


In [ ]:
# join and split numpy arrays
# the condition is the number of elements have to be the same
np1 = np.array([1, 2, 3, 4, 5])
np2 = np.array([6, 7, 8, 9, 10])
np3 = np.concatenate((np1, np2))
print(np3)

#for multidimensional array - 2d
np1 = np.array([[1, 2], [3, 4]])
np2 = np.array([[5, 6], [7, 8]])
np3 = np.concatenate((np1, np2), axis=1)
np4 = np.concatenate((np1, np2), axis=0)
print(np3)
print(np4)

#for multidimensional array - 3d
np1 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
np2 = np.array([[[9, 10], [11, 12]], [[13, 14], [15, 16]]])
np3 = np.concatenate((np1, np2), axis=0)
np4 = np.concatenate((np1, np2), axis=1)
np5 = np.concatenate((np1, np2), axis=2)
print(np3)
print(np4)
print(np5)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]]
[[[ 1  2]
  [ 3  4]
  [ 9 10]
  [11 12]]

 [[ 5  6]
  [ 7  8]
  [13 14]
  [15 16]]]
[[[ 1  2  9 10]
  [ 3  4 11 12]]

 [[ 5  6 13 14]
  [ 7  8 15 16]]]


In [ ]:
#np.stack
np1 = np.array([1, 2, 3, 4])
np2 = np.array([5, 6, 7, 8])

np3 = np.stack((np1, np2), axis=1)
print(np3)

#hstack - horizontal -- row
np4 = np.hstack((np1, np2))
print(np4)

#vstack - vertical --along
np5 = np.vstack((np1, np2))
print(np5)

#dstack - height
np6 = np.dstack((np1, np2))
print(np6)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]
[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]
[[[1 5]
  [2 6]
  [3 7]
  [4 8]]]


In [ ]:
#split array
np1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
np2 = np.array_split(np1, 3)
print(np2)
print(np2[0])
print(np2[1])
print(np2[2])

#split array - 2d
np1 = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
np2 = np.array_split(np1, 3, axis=0)
print(np2)
print(np2[0])
print(np2[1])
print(np2[2])

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
[1 2 3]
[4 5 6]
[7 8 9]
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]
[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 9 10]
 [11 12]]


In [ ]:
#sorting numpy arrays
#when we sort we return a copy of the original. Main data does not get changed
np1 = np.array([4, 6, 0, 1, 5, 9, 7, 8, 3, 2])
print("Original: ", np1)
print("Sorted: ", np.sort(np1))

Original:  [4 6 0 1 5 9 7 8 3 2]
Sorted:  [0 1 2 3 4 5 6 7 8 9]


In [ ]:
#sorting by alphabatical orders
np1 = np.array(["date", "elderberry", "banana", "apple", "cherry"])
print("Original: ", np1)
print("Sorted: ", np.sort(np1))

Original:  ['date' 'elderberry' 'banana' 'apple' 'cherry']
Sorted:  ['apple' 'banana' 'cherry' 'date' 'elderberry']


In [ ]:
#sorting a 2d array
#it just sorts each rows
np1 = np.array([[1, 4, 2, 5, 0], [3, 7, 6, 9, 8]])
print(np1)
print(np.sort(np1))

[[1 4 2 5 0]
 [3 7 6 9 8]]
[[0 1 2 4 5]
 [3 6 7 8 9]]


In [ ]:
#searching through numpy arrays
#it looks through the array and returns all the index number where the given elemnet is present
#it actually returns a tuple of index number
np1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(np1)
print(np.where(np1 == 5))

[1 2 3 4 5 6 7 8 9]
(array([4]),)


In [ ]:
#here's another example
np2 = np.array([1, 2, 3, 3, 1, 2, 5, 7, 3])
print(np2)
np3 = np.where(np2 == 3)
print(np3)
print(np3[0])

[1 2 3 3 1 2 5 7 3]
(array([2, 3, 8]),)
[2 3 8]


In [ ]:
#returns the actual items-that is kinda a basic code
np1 = np.array([1, 2, 3, 4, 5, 3, 2, 1, 3, 8, 3])
np2 = np.where(np1 == 3)
print(np2[0])
print(np1[np2[0]])


[ 2  5  8 10]
[3 3 3 3]


In [ ]:
#return the even item
#again it returns the index of the number that we are looking for
np1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
np2 = np.where(np1 % 2 == 0)
print(np2)
print(np2[0])

(array([1, 3, 5, 7]),)
[1 3 5 7]


In [ ]:
#same exact thing with the odd numbers
np1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
np2 = np.where(np1 % 2 != 0)
print(np2)
print(np2[0])

(array([0, 2, 4, 6, 8]),)
[0 2 4 6 8]


In [ ]:
#filtering numpy arrays with bookean index lists
np1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(np1)
np2 = [True, True, False, False, True, False, False, True, True, False]
print(np2)

print(np1[np2])

[ 1  2  3  4  5  6  7  8  9 10]
[True, True, False, False, True, False, False, True, True, False]
[1 2 5 8 9]


In [ ]:
#doing a task with it
np1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
filtered = []
for i in np1:
  if i%2==0:
    filtered.append(True)
  else:
    filtered.append(False)
print(np1)
print(filtered)
print(np1[filtered])

[ 1  2  3  4  5  6  7  8  9 10]
[False, True, False, True, False, True, False, True, False, True]
[ 2  4  6  8 10]


In [ ]:
#shortcut for this
np1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(np1)
filtered = (np1 % 2 != 0)
print(filtered)
print(np1[filtered])

[ 1  2  3  4  5  6  7  8  9 10]
[ True False  True False  True False  True False  True False]
[1 3 5 7 9]


In [ ]:
#functions in numpy
np1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(np1)

#shuffle- it shuffles the data
np.random.shuffle(np1)
print(np1)

#unique-gives the non-repeated data
np2 = np.unique(np1, return_index = True, return_counts=True)
print(np2)

# #resize
np1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
np2 = np.resize(np1, (2, 5))
print(np2)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  8 10  5  3  9  2  6  7  4]
(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), array([0, 6, 4, 9, 3, 7, 8, 1, 5, 2]), array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]))
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
#insert and delete in numpy array
np1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(np1)

#insert
np2 = np.insert(np1, 5, 100)
print(np2)

#to insert multiple elements
np3 = np.insert(np1, (2, 10), 99)
print(np3)

#for 2d insert
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
np3 = np.insert(arr, 2, 100, axis=1)
print(np3)

[ 1  2  3  4  5  6  7  8  9 10]
[  1   2   3   4   5 100   6   7   8   9  10]
[ 1  2 99  3  4  5  6  7  8  9 10 99]
[[  1   2 100   3   4   5]
 [  6   7 100   8   9  10]]
[ 1  2  3  4  5  7  8  9 10]
[ 1  3  5  6  7  8  9 10]


In [ ]:
#delete
np1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(np1)

np2 = np.delete(np1, 5)
print(np2)

#to delete multiple elements
np3 = np.delete(np1, (1, 3))
print(np3)

#for 2d delete
np3 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(np3)

np4 = np.delete(np3, 1, axis=0) #along row
np5 = np.delete(np3, 2, axis=1) #along column
print(np4)
print(np5)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  7  8  9 10]
[ 1  3  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[1 2 3 4 5]]
[[ 1  2  4  5]
 [ 6  7  9 10]]
