In [ ]:
#bubble sort
import numpy as np
def bubbleSort(arr):
    for i in range(0, len(arr)):
        for j in range(0, len(arr) - 1 - i):
            if arr[j] > arr[j + 1]:
                temp = arr[j]
                arr[j] = arr[j + 1]
                arr[j + 1] = temp
    return arr


arr = np.array([4, 6, 5, 8, 9, 0, 2, 1, 3, 7])
print(bubbleSort(arr))


[0 1 2 3 4 5 6 7 8 9]


In [3]:
#insertion sort
import numpy as np
def insertionSort(arr):
    for i in range(1, len(arr)):
        current_value = arr[i]
        neighbour_index = i-1
        while neighbour_index >= 0 and current_value < arr[neighbour_index]:
            arr[neighbour_index + 1] = arr[neighbour_index]
            neighbour_index -= 1
        arr[neighbour_index + 1] = current_value

    return arr


arr = np.array([4, 6, 5, 8, 9, 0, 2, 1, 3, 7])
print(insertionSort(arr))


[0 1 2 3 4 5 6 7 8 9]


In [ ]:
#selection sort
import numpy as np
def selectionSort(arr):
  for i in range(len(arr)):
    min_index = i
    for j in range(i+1, len(arr)):
      if arr[j] < arr[min_index]:
        min_index = j
    temp = arr[i]
    arr[i] = arr[min_index]
    arr[min_index] = temp
  return arr


arr = np.array([3, 3, 1, 0, 7])
print(selectionSort(arr))


[0 1 3 3 7]
